### ISSUE TITLE
Remove panic() from datamgr template and add proper log message and error responses

### ISSUE THREAD

**Issue by jscharber** [pavedroad-io/roadctl#85]
We have panic() in several places that need to be logged and a proper response returned to the client.

**Comment by jscharber** [comment]
The test template for Datamgr panics instead of logging a message.

https://github.com/pavedroad-io/templates/blob/53036d68b172206195fc52a6a29877ddf60ae0b7/microservices/ga/datamgr/template_test.go

Change to log an error like below

```go
t.Errorf("Expected response code %d. Got %d\n", expected, actual)
```

```go
//test getting a {{.Name}}
func TestGet{{.NameExported}}(t *testing.T) {
	clearTable()
	nt := New{{.NameExported}}()
	uid := add{{.NameExported}}(nt)
	statement := fmt.Sprintf({{.NameExported}}URL, uid)

	req, err := http.NewRequest("GET", statement, nil)
  if err != nil {
		panic(err)
  }

	response := executeRequest(req)

	checkResponseCode(t, http.StatusOK, response.Code)
}
```

**Comment by shgayle** [comment]
Hi John,

Not sure I will make the scrum today.

Will try to start doing a nightly fix on the tasks.

Also, can you do a version of the letter I requested?

Please let me know.

Thanks.
-Solomon
