### ISSUE TITLE
int validation failed

### ISSUE THREAD

**Issue by jscharber** [pavedroad-io/roadctl#97]
TODO
---
Step 1
- [x] Support integer as proper type and fix the validation error, int does not generate an error
- [x] Translate number to float
- [ ] Null should generate an error, saying use [omitempty](https://www.sohamkamani.com/golang/2018-07-19-golang-omitempty/) constraint on a supported type (string, integer, ...

--- 
Step 2
- [ ] Support array type

| JSON    | GO Type   | Today | Working | Tomorrow |
| -------- | ----------- | ------- | --------- | ----------- |
string  | string    | string | True | No Change |
integer | int       | int | Validation error | int fix validation |
number  | float  | number |Broken should be float | float |
boolean | bool      | boolean | No | bool |
time    | time.Time | time.Time | Yes | No Change |
**null    | Not supported | Untested | no| omitifempty set default zero nul or zero |
object  | struct | sub-table | Yes | No Change |
array   | list   | TODO | No | Implement list |
uuid | uuid.UUIDv4 | uuid.UUIDv4 " | Yes | No Change |

Current code in definitions
```go
var validColTypes = []string{
        "string",
        "number",
        "integer",
        "boolean",
        "time",
        "null",
        "uuid",
    }
```

**Comment by shgayle** [comment]
I was working with the past-definition pull request, so I push these changes there.
Is that OK?
